### ISSUE TITLE
Manual code review+SonarCloud bug fixes

### ISSUE THREAD

**Issue by david0192** [BME-MIT-IET/iet-hf-2023-tezauruszok#6]

**Comment by david0192** [comment]
teszt

**Comment by david0192** [comment]
"Save and reuse this random" bugfix folyamatban

**Comment by david0192** [comment]
String_and_boxed_types_compared_with_equal bugfix in progress

**Comment by david0192** [comment]
A "List<GeneticCode>" cannot contain a "Agent" bugfix in progress

**Comment by david0192** [comment]
Remove this assignment of "gt" code smell fix in progress

**Comment by balexhu** [comment]
Thanks for the fixes, looks nice!;)
